### PR TITLE
Fix/modify cards 375

### LINKED ISSUE #375: Modify Cards: Add Template Property and Fix Styles
- [x] Remove Border on Hover Effect from Cards 
- [x] Standardize Height for MainCard and CardWithHover Components
- [x] Add Template Property

### Remove Border on Hover Effect from Cards 

Currently, our card components display a border when hovered over. This behavior is inconsistent with our design guidelines which aim for a cleaner and more minimalistic interface.

### Standardize Height for MainCard and CardWithHover Components

To improve the visual consistency across our application's UI, we need to ensure that the MainCard and CardWithHover components have the same height. This change will align the appearance of these components when displayed side by side or in the same view, providing a cleaner layout.

### Add Template Property

To enhance the functionality of the CardWithHover component within our assets web application, we need to integrate the ITemplate (and  others) interface as a property. This will allow the component to utilize template-specific data directly, improving its interactivity and contextual usage throughout the application.

interface TemplateCardProps {
  template: ITemplate
  isPublished?: boolean
  onClickUse?: () => void //todo: remove optional later on
  onClickPreview?: () => void //todo: remove optional later on
  onClickCopyIcon?: () => void
  popoverItems?: ICustomPopoverItem[]
}

import { Box, Button, IconButton, Typography } from '@mui/material'
import React from 'react'

import CommunityIcon from 'app/components/Icons/communityIcon'
import CopyTemplateIcon from 'app/components/Icons/copyTemplateIcon'
import DotsIcon from 'app/components/Icons/dotsIcon'
import { ICustomPopoverItem, ITemplate } from 'types'

import CustomPopover from '../CustomPopover'

interface TemplateCardProps {
  template: ITemplate
  isPublished?: boolean
  onClickUse?: () => void //todo: remove optional later on
  onClickPreview?: () => void //todo: remove optional later on
  onClickCopyIcon?: () => void
  popoverItems?: ICustomPopoverItem[]
}

const TemplateCard: React.FC<TemplateCardProps> = ({
  template,
  isPublished,
  onClickUse,
  onClickPreview,
  onClickCopyIcon,
  popoverItems
}) => {
  const [anchorEl, setAnchorEl] = React.useState<HTMLButtonElement | null>(null)

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    setAnchorEl(event.currentTarget)
  }

  const handleClose = () => {
    setAnchorEl(null)
  }

  return (
    <Box
      sx={{
        borderRadius: '16px',
        background: '#ffffff',
        '&:hover .hover-it': {
          display: 'flex'
        },
        padding: 2,
        cursor: 'pointer'
      }}
    >
      <Box
        display='flex'
        flexDirection='column'
        justifyContent='space-between'
        minHeight={170}
      >
        <Box
          display='flex'
          justifyContent='space-between'
          alignItems='center'
          mb={2}
        >
          <CommunityIcon />
          <IconButton
            className='hover-it'
            sx={{
              display: anchorEl ? 'block' : 'none',
              p: 0,
              width: '32px',
              height: '32px',
              borderRadius: '50%'
            }}
            onClick={isPublished ? handleClick : onClickCopyIcon}
          >
            {isPublished ? <DotsIcon /> : <CopyTemplateIcon />}
          </IconButton>
        </Box>
        <Box>
          <Typography variant='body1' fontWeight={500}>
            {template.template_name}
          </Typography>
          <Typography variant='caption' sx={{ color: '#6B7280' }}>
            {template.description}
          </Typography>
        </Box>
        <Box
          className='hover-it'
          sx={{
            display: 'none',
            width: '100%',
            mt: 2,
            gap: 2
          }}
        >
          <Box sx={{ width: '100%' }}>
            <Button
              fullWidth
              variant='outlined'
              sx={{ borderRadius: '100px' }}
              onClick={onClickPreview}
            >
              Preview
            </Button>
          </Box>
          <Box sx={{ width: '100%' }}>
            <Button
              fullWidth
              variant='contained'
              sx={{ borderRadius: '100px', whiteSpace: 'nowrap' }}
              onClick={onClickUse}
            >
              Use Template
            </Button>
          </Box>
        </Box>
      </Box>
      {isPublished && popoverItems && (
        <CustomPopover
          templateId={template.id}
          items={popoverItems}
          anchorEl={anchorEl}
          onClose={handleClose}
        />
      )}
    </Box>
  )
}

export default TemplateCard

### PR DESCRIPTION
**Pull request by pzagardedukic**
### What does this PR do?

- Resolve #375 

- [x] Removed Border (box shadow) on Hover Effect from Cards 
- [x] Standardized Height for MainCard and CardWithHover Components
- [x] Added Template Properties
- [x] Updated stories and mdx files

Recent updates include various fixes and feature enhancements for the CardWithHover and related components. Key changes include the removal of the box shadow on hover, standardizing card heights, and introducing new properties like icon and background color. Documentation has been updated, and logic for the isPublished status and popover behavior was added. Additional fixes addressed popover positioning, card styling, and hover effects, ensuring a consistent and polished user interface.

### CODE REVIEW

**Review by AngeloCG97 — APPROVED** [review]

File: src/components/CardWithHover/index.tsx [hunk 1]
```diff
@@ -49,10 +51,11 @@ export const CardWithHover: React.FC<CardWithHoverProps> = ({
                     alignItems="center"
                     mb={2}
                 >
-                    {icon}
+                    <DocIcon />
```
Comment (AngeloCG97) [inline src/components/CardWithHover/index.tsx:54]: I believe that this value should not be fixed, it should be received as a parameter so that the component is more adjustable to different uses.

File: src/components/CardWithHover/index.tsx [hunk 2]
```diff
@@ -28,13 +30,13 @@ export const CardWithHover: React.FC<CardWithHoverProps> = ({
         <Box
             sx={{
                 borderRadius: "16px",
-                backgroundColor: backgroundColor || theme.palette.background.paper,
+                backgroundColor: theme.palette.background.paper,
```
Comment (AngeloCG97) [inline src/components/CardWithHover/index.tsx:33]: I believe that this value should not be fixed, it should be received as a parameter so that the component is more adjustable to different uses.

**Review by AngeloCG97 — APPROVED** [review]
