### PR TITLE
Fix/lendborrow component does not accept formatted inputs 80

### LINKED ISSUE #80: LendBorrow component does not accept formatted inputs
Inputs like `12.123` fails to render correctly

### PR DESCRIPTION
**Pull request by JAMares**
### What does this PR do?

- Resolve #80

### Steps to test

1. Run yarn storybook
2. Check changes

Before:
imagen

Now:
imagen

#### CheckList

- [X] Follow proper Markdown format
- [X] Content is available in all languages
- [X] The content is adequate
- [X] I Ran a spell check
- [X] I included test coverage

### CODE REVIEW

File: src/components/Input/index.tsx [hunk 1]
```diff
@@ -1,19 +1,67 @@
...
+  type,
+  onChange,
+  setFormat,
+  precision = -1,
+}: IInput) => {
+  const [inputValue, setInputValue] = useState<InputValue>(value);
+
+  const addPrecision = (value: string, precision: number): string => {
+    if (precision < 0) return value;
+    const numero = parseFloat(value.replace(/[^0-9]/g, ""));
```
Comment (leisterfrancisco) [inline src/components/Input/index.tsx:24]: spanish?

**Review by leisterfrancisco — APPROVED** [review]

**Review by xavier506 — APPROVED** [review]
LGTM
